### PR TITLE
Fix misleading pattern name and documentation

### PR DESCRIPTION
**Pull request by mrezzamoradi**
The `ALLOWED_CHARS_PATTERN` and `regex_pattern` are actually disallowed characters in the final slug.
 Also since the code lowers the case in line 141,  there's no need for a separate regex pattern for lowercase strings

### CODE REVIEW

**Comment by un33k** [comment]
@mrezzamoradi Thank you for raising this PR.

However, the `pattern` is to match all chars we want to `keep`.
Anything else outside the pattern will be replaced with the `separator`.

```python
 # replace all other unwanted characters
    if lowercase:
        pattern = regex_pattern or ALLOWED_CHARS_PATTERN
    else:
        pattern = regex_pattern or ALLOWED_CHARS_PATTERN_WITH_UPPERCASE
    text = re.sub(pattern, DEFAULT_SEPARATOR, text). # <-- look here 
```

Example: 
```python
>>> allowedPattern = re.compile(r'[^-a-z0-9]+')
>>> text = 'Aboo$%$%$%9-999--asdfasfd'
>>> unwantedRemoved = re.sub(allowedPattern, '-', text)
>>> print(unwantedRemoved)
'-boo-9-999--asdfasfd'
>>>
```

**Comment by un33k** [comment]
@mrezzamoradi 

Once again thank you for taking the time to raise this PR.

With that said, I am going to closing this PR for now.
If the above explanation is not sufficient, or you have new updates, feel free to raise an updated PR or a new one.

Should you have time to add github actions to this repo, I would appreciate it as well. 
Thx

**Comment by mrezzamoradi** [comment]
> @mrezzamoradi Thank you for raising this PR.
> 
> However, the `pattern` is to match all chars we want to `keep`. Anything else outside the pattern will be replaced with the `separator`.
> 
> **Code:**
> 
> ```python
>  # replace all other unwanted characters
>     if lowercase:
>         pattern = regex_pattern or ALLOWED_CHARS_PATTERN
>     else:
>         pattern = regex_pattern or ALLOWED_CHARS_PATTERN_WITH_UPPERCASE
>     text = re.sub(pattern, DEFAULT_SEPARATOR, text). # <-- look here 
> ```
> 
> **Example:**
> 
> ```python
> >>> allowedPattern = re.compile(r'[^-a-z0-9]+')
> >>> text = 'Aboo$%$%$%9-999--asdfasfd'
> >>> unwantedRemoved = re.sub(allowedPattern, '-', text)
> >>> print(unwantedRemoved)
> '-boo-9-999--asdfasfd'
> >>>
> ```
> 
> **Also:** Case sensitive needs to follow the `lowercase` flag (default = False). This is specially true when the `separator` is something like: `ABZZzzzzDDD'; Please refer to the tests here. https://github.com/un33k/python-slugify/blob/master/test.py#L97

Thanks for your comment @un33k
Still you might have either misnamed the ALLOWED_CHARS_PATTERN or misunderstood the `re.sub` function. let's dig into it:
- `[^-a-z0-9]+` simply means match any character that **is not** in the list of dash, a-z, or 0-9. It means characters like `?<>!@`. Now is the code supposed to keep the latter characters? I guess not. Those are the characters you want to ignore/disallow and replace them by a `separator`

- `re.sub(pattern, repl, string)` is simply regex substitution (replacement) function. It replaces any character in the `string` that matches the `pattern`, with `repl`. Now again obviously the aim of `re.sub(pattern, DEFAULT_SEPARATOR, text)` is not to keep the pattern in the text. It's quite the opposite, to replace/remove them from the text.

I hope this explanation brings some light on the confusion here. The same explanation can explain some part of why I've removed the lowercase regex pattern (because the matching characters would always be a subset of the matching characters when using `ALLOWED_CHARS_PATTERN_WITH_UPPERCASE`) . Also note that the current default value of `lowercase` flag is True and it converts the text to lowercase before any substitution of patterns.

**Comment by mrezzamoradi** [comment]
btw this PR passes all the tests

**Comment by un33k** [comment]
@mrezzamoradi I enabled github actions to ensure we have a trusted CI. 

As soon as the tests passed, I decided to pull your request in.
https://github.com/un33k/python-slugify/tree/v6.0.1

I do appreciate your contribution.

**Pull request merged**
