### PR TITLE
Drop support for EOL Python 2.6 and 3.2-2.4

### PR DESCRIPTION
**Pull request by hugovk**
Python 2.6 and 3.3 were removed in https://github.com/un33k/python-slugify/pull/63, so this removes their Trove classifiers.

This also:

* Removes a duplicate test class

* Upgrade Python syntax with [pyupgrade](https://github.com/asottile/pyupgrade)

* Upgrade PyPy and PyPy3 (6.0.0 to 7.1.1) and test 3.8 beta on the CI

* Add `python_requires` to help pip

### CODE REVIEW

**Comment by un33k** [comment]
@hugovk.  May I ask you to raise the PR against the staging branch instead ?  Thank you.

**Comment by hugovk** [comment]
I've switched the base branch to staging. 

May I suggest changing the default branch in the repo settings to staging? That way future PRs will be made to staging in the future. Thanks!

**Comment by un33k** [comment]
I like master branch as default, but I wish there was a way to include a default for incoming PRs.  Each incoming PR needs to be tested followed by a version bump and only then it can be promoted to master.

**Comment by un33k** [comment]
Thank you for your contribution. Version 4.0.0 is pushed. https://github.com/un33k/python-slugify/tree/4.0.0

**Comment by hugovk** [comment]
You're welcome!

**Pull request merged**
