### PR TITLE
Add UniqueSlugify for generating unique slugs

### PR DESCRIPTION
**Pull request by sloria**

### CODE REVIEW

**Comment by un33k** [comment]
Unfortunately the uniqueness cannot be enforced throw restart of applications.  As such it is best to handle it on case-by-case basis.

If you need this for Django, you can refer to https://github.com/un33k/django-uuslug

**Comment by sloria** [comment]
There are use cases when you don't global uniqueness and per-process uniqueness is desired. For example: generating slugs for headers within a user-submitted document such as a README. In my case, users build a form by providing form field types and human-readable labels ("Email address") from which machine-readable IDs ("email-address-1") must be generated. The IDs should be unique within a form but not globally unique.

**Comment by un33k** [comment]
Only good for single instance applications. Out of sope for this module. Thx

**Comment by sloria** [comment]
The use cases I mentioned aren't specific to single-instance apps. I respect if you think this is out of scope for this library, though. Thanks anyway.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this PR to https://github.com/un33k/python-slugify/pull/191.

A stateful uniqueness API remains deferred. Collision handling belongs to the application; no database uniqueness guarantee is provided.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️

**Pull request closed without merging**
