### PR TITLE
Replace flake8 and pycodestyle with ruff

### PR DESCRIPTION
**Pull request by cclauss**
[Ruff](https://beta.ruff.rs) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) including bandit, flake8, isort, pylint, and pyupgrade and is written in Rust for speed.
Also added rules for pylint conventions, pylint errors, and pylint warnings.

### CODE REVIEW

**Comment by mrezzamoradi** [comment]
This is actually nice. The difference in speed is noticeable.

**Comment by un33k** [comment]
@cclauss, @mrezzamoradi django-ipware might be on its way to being deprecated.

With that said, I have a python package that is going to replace it.

Have a look at [python-ipware](https://github.com/un33k/django-ipware) and if works for you switch to it.

Feedback is welcomed.

**Comment by jdevera** [comment]
Thank you for this PR!
Let's say there is an appetite for this particular change.
For the PR to be merged, though, there would be a few things to take care of, please let me know if you are happy to take them on:

1. Ensure a 1-1 correspondence between the current settings and the new ones with ruff. In his case, the command introduces a line length limit of 117 whereas this project explicitly disables line length checks currently. Generally, these changes should not be introduced without mentioning them explicitly.
1. Run the command on the repo and contribute also the changes that will fix violations. In his case, two violations appear, and this would result in an immediate CI failure upon merging this PR.
1. Also change non-functional code that refers to the changes you are making. There is a title for the step you are changing that refers to flake8 and should not. But also there are other places in the repo that refer to the tools you are replacing, like the dev.requirements file and the format.sh script

**Comment by cclauss** [comment]
> this project explicitly disables line length checks currently

Disables line length checks (and code complexity checks) is a bad idea because it encourages further bad behavior.  If instead we set an upper limit then if someone wants to contribute longer lines (or more complex code) then they need to justify in their pull request why they _need_ messier code then is already in the codebase.

> contribute also the changes that will fix violations

Rome was not built it a day.  A pull request that improves the codebase by setting up guardrails moves the project forward.  Fixing the two ignored issues will make for a much more complicated pull request to get reviewed and merged.  Given that this pull request has taken more than 5 months to get reviewed, keeping the changes simple is goodness.

> other places in the repo that refer to the tools you are replacing, like the dev.requirements file and the format.sh script

This GitHub Action does not use `dev.requirements` and ruff is not a code formatter.  Black is.

**Comment by un33k** [comment]
Contributors/Collaborators - Please feel free to approve and merge.

One question: Do we need to ensure 'ruff' is installed on all systems without it being in the requirements.txt

**Comment by cclauss** [comment]
> Do we need to ensure 'ruff' is installed on all systems without it being in the requirements.txt

Perhaps ruff and black and similar tools should be run in [pre-commit](https://pre-commit.com) to ensure the same versions are installed on all contributing and testing machines.

**Comment by jdevera** [comment]
> Fixing the two ignored issues will make for a much more complicated pull request to get reviewed and merged.

My bad, I did not mean the ignored issues, but it was a misunderstanding coming 100% from me. My working tree was dirty, and the command caught some errors in some experimental test files I had around. No real issues here.

> Given that this pull request has taken more than 5 months to get reviewed, keeping the changes simple is goodness.

Regardless of the misunderstanding, I believe the time it takes to review PRs here depends more on the availability of the maintainers than on anything else.

> Do we need to ensure 'ruff' is installed on all systems without it being in the requirements.txt

I would add a line to the dev.requirements.txt, with a specific version, and I think this PR would benefit from locking on the version of ruff in the workflow file too.

RE: the line length check. I'm all for it and this could then be the last time two humans have a conversation about such a boring topic on this repo 🥂 .

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this PR to https://github.com/un33k/python-slugify/pull/191.

Ruff migration remains deferred. Existing lint tools are retained; #191 does not implement this tooling migration.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️

**Pull request merged**
