### PR TITLE
BF(dependencies)| Bump `text_unidecode` version

### PR DESCRIPTION
**Pull request by koolfunky**
1.2 -> 1.3

### CODE REVIEW

**Comment by koolfunky** [comment]
Fixes #82

**Comment by un33k** [comment]
Please issue PR to the staging branch ...

**Comment by koolfunky** [comment]
@un33k is it ok like this ?

**Comment by un33k** [comment]
Thank you for your contribution. I will publish this on the next release cycle. Soon.

**Comment by un33k** [comment]
Please upgrade to https://github.com/un33k/python-slugify/tree/3.0.4

**Pull request merged**
