### PR TITLE
Add parameter 'save_order'.

### PR DESCRIPTION
**Pull request by dioexul**
If save_order == True then order of words of output string will be like order of input string.

### CODE REVIEW

**Comment by un33k** [comment]
Your test cases are in Russian (I think) and I don't know what your save_order is trying  to achieve?
If you could provide some English example of the problem and the solution, it would be great.

**Comment by dioexul** [comment]
Done. This parameter controls order in output string. If save_order and word_boundary are true then "three" (len = 5) does not change to "four" (len = 4) for max_length=12 and text = 'one two three four five'.

**Comment by un33k** [comment]
Pushed to pypi for your use.
Thank you for your contribution.

**Comment by dioexul** [comment]
Thank you for Slugify =)

**Pull request merged**
