### PR TITLE
quotes are replaced by -, bump to 1.1.4

### LINKED ISSUE #17: \' shoud be replaced by separator
In your example:

~~~python
txt = 'C\'est déjà l\'été.'
r = slugify(txt)
self.assertEqual(r, "cest-deja-lete")
~~~

I believe the result should be 'c-est-deja-l-ete', not 'cest-deja-lete'.

### PR DESCRIPTION
**Pull request by nMustaki**
FIX #17

### CODE REVIEW

**Comment by nMustaki** [comment]
test_cyrillic_text is failling, but I don't understand why any letter in 'Компьютер' should match a quote, is it normal ?

**Comment by un33k** [comment]
(компьютер) is first converted to (komp'yuter), and you can see why it is matching a quote.

**Comment by nMustaki** [comment]
Ok thanks. It is meaningfull in this language to replace the quote by a
dash ?


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/

**Comment by un33k** [comment]
Don't speak Russian, but I know it doesn't make sense to have a computer written as comp-uter. Same goes for Kompyuter vs. Komp-yuter.

I suggest that users of slugify pre-process the text as per their locale prior to calling slugify.

**Comment by nMustaki** [comment]
So I grabbed a Russian and the comma is a phonic (not sure it's the right word...) accent.
Maybe an option could be given when creating the slugify object, retrocompatibility would be respected and us froggies would have our dash?

**Comment by nMustaki** [comment]
I am closing this one to replace it by #20

**Comment by un33k** [comment]
https://github.com/un33k/python-slugify/issues/17

**Comment by un33k** [comment]
Available in version 1.2.0.

**Pull request closed without merging**
